### ISSUE TITLE
show the delay next to the departure time

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/vbb-web#1]
When using public transport, I is quite helpful not only to have the realtime departure of a vehicle, but also *how much it is delayed*, to estimate if the delay will increase further. **It would be nice to show the delay next to the departure time, just like the apps do: Show a red `+2`.**

[The data we render has a `delay`](https://github.com/derhuerst/vbb-hafas/blob/4630f416f82392bffc0c6e6a16dc78dc90c1529f/docs/departures.md#response), which we can turn into a human-readable time string using [`ms`](https://www.npmjs.com/package/ms)

**Comment by gfranco93** [comment]
I would like to work on it
