### ISSUE TITLE
convenience feature: add a "more departures" link below the results

### ISSUE THREAD

**Issue by derhuerst** [derhuerst/vbb-web#5]

**Comment by carlosnufe** [comment]
Hi @derhuerst,

Some questions,
- What style should follow this link? Plain text ? A box like previous box link saying 'Show departures' ?
- The most important, this link should be to what? Maybe empty link ('#') ?

**Comment by derhuerst** [comment]
> What style should follow this link? Plain text ? A box like previous box link saying 'Show departures' ?

I don't really have an opinion on that. Keep it consistent with the existing UI, so links blue and buttons red.

> The most important, this link should be to what? Maybe empty link ('#') ?

You can generate a link that contains a new `when` parameter with the value of the last departure time. This can be done on the server side, to get a nice, real link.

**Comment by derhuerst** [comment]
closed by #6.
